name: COF Test Suite

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdb-dev libgdbm-dev
    
    - name: Install Perl dependencies
      run: |
        cpanm --notest Module::Build
        cpanm --notest Test::More
        cpanm --notest Params::Validate
        cpanm --notest File::HomeDir
        cpanm --notest Try::Tiny
        cpanm --notest Carp::Always
        cpanm --notest Getopt::Long
        cpanm --notest JSON::PP
        cpanm --notest Pod::Usage
        cpanm --notest File::Spec
        # Critical database dependencies
        cpanm --notest DB_File
        cpanm --notest GDBM_File
        # Skip Wx dependency for headless testing
    
    - name: Build project
      run: |
        # Try building with full dependencies, fallback if GUI deps fail
        perl Build.PL || echo "Build.PL failed, continuing with tests only"
        perl Build || echo "Build failed, continuing with tests only"
    
    - name: Run test suite
      run: |
        cd tests
        perl run_all_tests.pl
    
    - name: Test utilities
      run: |
        # Test spellchecker utility
        perl util/spellchecker_utils.pl --suggest cjupe --format json
        
        # Test radixtree utility  
        perl util/radixtree_utils.pl --word cjupe --format json
        
        # Test encoding utility
        perl util/encoding_utils.pl --suggest cjupe

  test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup Perl on Windows
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
        distribution: strawberry
    
    - name: Install Perl dependencies
      run: |
        cpanm --notest Module::Build
        cpanm --notest Test::More
        cpanm --notest Params::Validate
        cpanm --notest File::HomeDir
        cpanm --notest Try::Tiny
        cpanm --notest Carp::Always
        cpanm --notest Getopt::Long
        cpanm --notest JSON::PP
        cpanm --notest Pod::Usage
        cpanm --notest File::Spec
        # Critical database dependencies - included in Strawberry Perl
        cpanm --notest DB_File
      shell: powershell
    
    - name: Build project
      run: |
        try { perl Build.PL } catch { Write-Host "Build.PL failed, continuing with tests only" }
        try { perl Build } catch { Write-Host "Build failed, continuing with tests only" }
      shell: powershell
    
    - name: Run test suite
      run: |
        cd tests
        perl run_all_tests.pl
      shell: powershell
    
    - name: Test utilities
      run: |
        perl util/spellchecker_utils.pl --suggest cjupe --format json
        perl util/radixtree_utils.pl --word cjupe --format json
        perl util/encoding_utils.pl --suggest cjupe
      shell: powershell